//! The handler every bridge call goes through.
//!
//! flutter_rust_bridge generates a default one unless the API defines
//! `FLUTTER_RUST_BRIDGE_HANDLER` itself, which this module does for one reason:
//! on the web, the default runs each non-async API function on a web-worker
//! pool while every async one runs on the browser's main thread
//! (`wasm_bindgen_futures::spawn_local`). Both reach the same `std::sync` locks
//! — the stores, and the `RwLock` behind each opaque type's object pool — and
//! when the main thread finds one held by a worker, Rust waits with
//! `memory.atomic.wait32`, which the browser forbids there. The page traps with
//! "Atomics.wait cannot be called in this context": a blank page at startup or
//! a dead bridge mid-session (#294).
//!
//! So on the web a non-async function runs exactly like an async one, on the
//! main thread, and no Rust ever runs on a worker: one thread cannot contend
//! with itself. Native targets keep the default, where a contended lock costs a
//! wait, not the page.

use flutter_rust_bridge::handler::{Executor, TaskContext, TaskInfo, TaskRetFutTrait};
#[cfg(target_family = "wasm")]
use flutter_rust_bridge::{
    handler::{NoOpErrorListener, SimpleExecutor, SimpleHandler},
    SimpleAsyncRuntime,
};
use flutter_rust_bridge::{BaseCodec, SimpleThreadPool};
use std::future::Future;

use crate::frb_generated::FLUTTER_RUST_BRIDGE_CODEGEN_VERSION;

/// Runs a non-async task through the async path of the executor it wraps.
///
/// Used on the web only; compiled everywhere so its routing is unit-tested.
#[flutter_rust_bridge::frb(ignore)]
#[cfg_attr(not(target_family = "wasm"), allow(dead_code))]
pub struct MainThreadExecutor<E>(E);

impl<E: Executor> Executor for MainThreadExecutor<E> {
    fn execute_normal<Rust2DartCodec, TaskFn>(&self, task_info: TaskInfo, task: TaskFn)
    where
        TaskFn: FnOnce(TaskContext) -> Result<Rust2DartCodec::Message, Rust2DartCodec::Message>
            + Send
            + 'static,
        Rust2DartCodec: BaseCodec,
    {
        self.0
            .execute_async::<Rust2DartCodec, _, _>(task_info, move |context| async move {
                task(context)
            });
    }

    fn execute_sync<Rust2DartCodec, SyncTaskFn>(
        &self,
        task_info: TaskInfo,
        sync_task: SyncTaskFn,
    ) -> Rust2DartCodec::Message
    where
        SyncTaskFn: FnOnce() -> Result<Rust2DartCodec::Message, Rust2DartCodec::Message>,
        Rust2DartCodec: BaseCodec,
    {
        self.0
            .execute_sync::<Rust2DartCodec, _>(task_info, sync_task)
    }

    fn execute_async<Rust2DartCodec, TaskFn, TaskRetFut>(&self, task_info: TaskInfo, task: TaskFn)
    where
        TaskFn: FnOnce(TaskContext) -> TaskRetFut + Send + 'static,
        TaskRetFut: Future<Output = Result<Rust2DartCodec::Message, Rust2DartCodec::Message>>
            + TaskRetFutTrait,
        Rust2DartCodec: BaseCodec,
    {
        self.0
            .execute_async::<Rust2DartCodec, _, _>(task_info, task)
    }
}

/// The same check the generated default handler makes: bindings generated by
/// another codegen version do not match this runtime.
fn assert_codegen_matches_runtime() {
    assert_eq!(
        FLUTTER_RUST_BRIDGE_CODEGEN_VERSION,
        flutter_rust_bridge::for_generated::FLUTTER_RUST_BRIDGE_RUNTIME_VERSION,
        "Please ensure flutter_rust_bridge's codegen ({}) and runtime ({}) versions are the same",
        FLUTTER_RUST_BRIDGE_CODEGEN_VERSION,
        flutter_rust_bridge::for_generated::FLUTTER_RUST_BRIDGE_RUNTIME_VERSION,
    );
}

#[cfg(not(target_family = "wasm"))]
flutter_rust_bridge::for_generated::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: flutter_rust_bridge::DefaultHandler<SimpleThreadPool> = {
        assert_codegen_matches_runtime();
        flutter_rust_bridge::DefaultHandler::new_simple(Default::default())
    };
}

#[cfg(target_family = "wasm")]
thread_local! {
    // Required by `SimpleExecutor`'s type, never used: `MainThreadExecutor`
    // never hands it a task, so no worker is ever spawned.
    static THREAD_POOL: SimpleThreadPool = Default::default();
}

#[cfg(target_family = "wasm")]
type WebExecutor = MainThreadExecutor<
    SimpleExecutor<
        NoOpErrorListener,
        &'static std::thread::LocalKey<SimpleThreadPool>,
        SimpleAsyncRuntime,
    >,
>;

#[cfg(target_family = "wasm")]
flutter_rust_bridge::for_generated::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: SimpleHandler<WebExecutor, NoOpErrorListener> = {
        assert_codegen_matches_runtime();
        SimpleHandler::new(
            MainThreadExecutor(SimpleExecutor::new(
                NoOpErrorListener,
                &THREAD_POOL,
                SimpleAsyncRuntime,
            )),
            NoOpErrorListener,
        )
    };
}

#[cfg(test)]
mod tests {
    use super::*;
    use flutter_rust_bridge::for_generated::SseCodec;
    use flutter_rust_bridge::handler::FfiCallMode;
    use flutter_rust_bridge::Rust2DartMessageTrait;
    use futures_util::FutureExt;
    use std::sync::atomic::{AtomicBool, Ordering};
    use std::sync::{Arc, Mutex};

    /// Records which path each task took, and runs what it is handed.
    #[derive(Default)]
    struct Recorder {
        calls: Mutex<Vec<&'static str>>,
    }

    impl Recorder {
        fn calls(&self) -> Vec<&'static str> {
            self.calls.lock().unwrap().clone()
        }
    }

    impl Executor for &Recorder {
        fn execute_normal<C, F>(&self, _: TaskInfo, task: F)
        where
            F: FnOnce(TaskContext) -> Result<C::Message, C::Message> + Send + 'static,
            C: BaseCodec,
        {
            self.calls.lock().unwrap().push("normal");
            let _ = task(TaskContext::new());
        }

        fn execute_sync<C, F>(&self, _: TaskInfo, sync_task: F) -> C::Message
        where
            F: FnOnce() -> Result<C::Message, C::Message>,
            C: BaseCodec,
        {
            self.calls.lock().unwrap().push("sync");
            sync_task().unwrap_or_else(|e| e)
        }

        fn execute_async<C, F, Fut>(&self, _: TaskInfo, task: F)
        where
            F: FnOnce(TaskContext) -> Fut + Send + 'static,
            Fut: Future<Output = Result<C::Message, C::Message>> + TaskRetFutTrait,
            C: BaseCodec,
        {
            self.calls.lock().unwrap().push("async");
            let _ = task(TaskContext::new())
                .now_or_never()
                .expect("a wrapped normal task is ready at once");
        }
    }

    fn task_info() -> TaskInfo {
        TaskInfo {
            port: None,
            debug_name: "test",
            mode: FfiCallMode::Normal,
        }
    }

    type Message = <SseCodec as BaseCodec>::Message;

    #[test]
    fn a_normal_task_runs_on_the_async_path() {
        let recorder = Recorder::default();
        let executor = MainThreadExecutor(&recorder);
        let ran = Arc::new(AtomicBool::new(false));
        let ran_in_task = ran.clone();

        executor.execute_normal::<SseCodec, _>(task_info(), move |_| {
            ran_in_task.store(true, Ordering::SeqCst);
            Ok(Message::simplest())
        });

        assert_eq!(recorder.calls(), vec!["async"]);
        assert!(ran.load(Ordering::SeqCst));
    }

    #[test]
    fn sync_and_async_tasks_keep_their_own_paths() {
        let recorder = Recorder::default();
        let executor = MainThreadExecutor(&recorder);

        let _ = executor.execute_sync::<SseCodec, _>(task_info(), || Ok(Message::simplest()));
        executor
            .execute_async::<SseCodec, _, _>(task_info(), |_| async { Ok(Message::simplest()) });

        assert_eq!(recorder.calls(), vec!["sync", "async"]);
    }
}
