/// Community Profile API — onboarding, QR decoding, and community settings.
///
/// Implements parsing, signature verification, and application of Community
/// Profiles generated by Mostro operators (e.g. from Mostro Community Manager for Umbrel).
///
/// Supported input formats:
/// - Deep links: `mostro://community/<payload>`
/// - Web links: `https://mostro.network/c/<payload>`
/// - Base64 or Base64URL encoded JSON
/// - Raw JSON strings
/// - Nostr NIP-19 profiles: `nostr:nprofile1...` or `nprofile1...`
use anyhow::{bail, Result};
use nostr_sdk::prelude::*;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::db::{settings_keys, Storage};

/// A community configuration profile signed by the community node operator.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct CommunityProfile {
    /// Schema version (currently 1).
    pub version: u32,
    /// Human-readable community name (e.g. "Bitcoin Medellín").
    pub name: String,
    /// 64-character lowercase hex Nostr public key of the Mostro daemon.
    pub pubkey: String,
    /// List of WebSocket relay URLs used by the community.
    pub relays: Vec<String>,
    /// Primary ISO 4217 fiat currency code (e.g. "COP", "USD", "EUR").
    pub currency: String,
    /// Prioritized accepted payment methods for this community.
    pub payment_methods: Vec<String>,
    /// Community trade fee in basis points (e.g. 60 = 0.6%).
    pub fee_bps: u32,
    /// Required anti-abuse guarantee / bond percentage (e.g. 3 = 3%).
    pub bond_percent: u32,
    /// Optional community website link.
    pub website: Option<String>,
    /// Optional operator contact info (Nostr npub, Telegram, or email).
    pub contact: Option<String>,
    /// 64-byte hex (128 char) Schnorr signature over the canonical payload.
    pub signature: String,
}

// ── Canonical Digest & Signature ─────────────────────────────────────────────

/// Compute the SHA-256 digest of the canonical profile fields for signature verification.
pub fn canonical_digest(profile: &CommunityProfile) -> [u8; 32] {
    let mut hasher = Sha256::new();
    let mut sorted_relays = profile.relays.clone();
    sorted_relays.sort();
    let canonical = format!(
        "v={}&name={}&pubkey={}&relays={}&currency={}&payment_methods={}&fee_bps={}&bond_percent={}&website={}&contact={}",
        profile.version,
        profile.name.trim(),
        profile.pubkey.trim().to_lowercase(),
        sorted_relays.join(","),
        profile.currency.trim().to_uppercase(),
        profile.payment_methods.join(","),
        profile.fee_bps,
        profile.bond_percent,
        profile.website.as_deref().unwrap_or("").trim(),
        profile.contact.as_deref().unwrap_or("").trim(),
    );
    hasher.update(canonical.as_bytes());
    hasher.finalize().into()
}

/// Verify the Schnorr signature of a CommunityProfile against its `pubkey`.
///
/// Returns `true` if the signature is valid, `false` otherwise.
pub fn verify_community_signature(profile: &CommunityProfile) -> bool {
    let sig_hex = profile.signature.trim();
    if sig_hex.is_empty() {
        return false;
    }

    let Ok(sig_bytes) = hex::decode(sig_hex) else {
        return false;
    };

    let Ok(sig) = k256::schnorr::Signature::try_from(sig_bytes.as_slice()) else {
        return false;
    };

    let Ok(pk) = PublicKey::from_hex(&profile.pubkey) else {
        return false;
    };

    let Ok(verifying_key) = k256::schnorr::VerifyingKey::from_bytes(&pk.to_bytes()) else {
        return false;
    };

    let digest = canonical_digest(profile);
    verifying_key.verify_raw(&digest, &sig).is_ok()
}

// ── Parsing & Decoding ───────────────────────────────────────────────────────

/// Parse a raw input string (deep link, URL, Base64/Base64URL JSON, or nprofile)
/// into a validated [`CommunityProfile`].
///
/// **Errors**:
/// - `InvalidCommunityPayload`: Malformed JSON or unreadable encoding.
/// - `InvalidPubkey`: If the embedded pubkey is not a valid 64-char hex or Nostr key.
/// - `InvalidCurrency`: If currency is not a 3-letter ISO code.
pub fn parse_community_payload(input: String) -> Result<CommunityProfile> {
    let trimmed = input.trim();

    // 1. Strip deep-link or web URL schemes
    let content = if let Some(stripped) = trimmed.strip_prefix("mostro://community/") {
        stripped
    } else if let Some(stripped) = trimmed.strip_prefix("https://mostro.network/c/") {
        stripped
    } else if let Some(stripped) = trimmed.strip_prefix("http://mostro.network/c/") {
        stripped
    } else {
        trimmed
    };

    // 2. Check for NIP-19 nprofile or npub fallback
    if content.starts_with("nostr:nprofile1")
        || content.starts_with("nprofile1")
        || content.starts_with("nostr:npub1")
        || content.starts_with("npub1")
    {
        return parse_nip19_community(content);
    }

    // 3. Attempt direct JSON parse
    if content.starts_with('{') && content.ends_with('}') {
        return parse_and_validate_json(content);
    }

    // 4. Attempt Base64 / Base64URL decode
    use base64::engine::general_purpose::{STANDARD, URL_SAFE, URL_SAFE_NO_PAD};
    use base64::Engine;

    let decoded_bytes = URL_SAFE_NO_PAD
        .decode(content)
        .or_else(|_| URL_SAFE.decode(content))
        .or_else(|_| STANDARD.decode(content));

    if let Ok(bytes) = decoded_bytes {
        if let Ok(json_str) = String::from_utf8(bytes) {
            if json_str.trim().starts_with('{') {
                return parse_and_validate_json(&json_str);
            }
        }
    }

    bail!("InvalidCommunityPayload: unrecognized community format or invalid encoding")
}

fn parse_and_validate_json(json_str: &str) -> Result<CommunityProfile> {
    let mut profile: CommunityProfile = serde_json::from_str(json_str)
        .map_err(|e| anyhow::anyhow!("InvalidCommunityPayload: JSON parse error: {e}"))?;

    // Normalize pubkey to lowercase hex
    let pk = PublicKey::parse(&profile.pubkey)
        .map_err(|e| anyhow::anyhow!("InvalidPubkey: invalid community pubkey: {e}"))?;
    profile.pubkey = pk.to_hex();

    // Validate currency
    let cur = profile.currency.trim().to_uppercase();
    if cur.len() != 3 || !cur.chars().all(|c| c.is_ascii_uppercase()) {
        bail!("InvalidCurrency: '{}' must be a 3-letter ISO code", profile.currency);
    }
    profile.currency = cur;

    // Filter and normalize valid relays (strip trailing slash for consistency)
    profile.relays = profile
        .relays
        .into_iter()
        .map(|r| r.trim().trim_end_matches('/').to_string())
        .filter(|r| r.starts_with("ws://") || r.starts_with("wss://"))
        .collect();

    Ok(profile)
}

/// Fallback for scanning a bare Nostr profile (`nostr:nprofile1...` or `npub1...`).
fn parse_nip19_community(input: &str) -> Result<CommunityProfile> {
    let clean = input.strip_prefix("nostr:").unwrap_or(input);

    if clean.starts_with("nprofile1") {
        let profile = Nip19Profile::from_bech32(clean)
            .map_err(|e| anyhow::anyhow!("InvalidCommunityPayload: invalid nprofile: {e}"))?;

        let relays: Vec<String> = profile
            .relays
            .into_iter()
            .map(|r| r.to_string().trim().trim_end_matches('/').to_string())
            .collect();

        Ok(CommunityProfile {
            version: 1,
            name: "Community Node".to_string(),
            pubkey: profile.public_key.to_hex(),
            relays,
            currency: "USD".to_string(),
            payment_methods: Vec::new(),
            fee_bps: 60,
            bond_percent: 3,
            website: None,
            contact: None,
            signature: String::new(),
        })
    } else if clean.starts_with("npub1") {
        let pk = PublicKey::from_bech32(clean)
            .map_err(|e| anyhow::anyhow!("InvalidPubkey: invalid npub: {e}"))?;

        Ok(CommunityProfile {
            version: 1,
            name: "Community Node".to_string(),
            pubkey: pk.to_hex(),
            relays: Vec::new(),
            currency: "USD".to_string(),
            payment_methods: Vec::new(),
            fee_bps: 60,
            bond_percent: 3,
            website: None,
            contact: None,
            signature: String::new(),
        })
    } else {
        bail!("InvalidCommunityPayload: unsupported nostr URI")
    }
}

// ── Application & Persistence ────────────────────────────────────────────────

/// Apply a confirmed [`CommunityProfile`] to the active application state:
/// 1. Activates the community Mostro node pubkey.
/// 2. Sets the default fiat currency.
/// 3. Registers community relays in the pool.
/// 4. Persists the active profile and accepted payment methods.
pub async fn apply_community_profile(profile: CommunityProfile) -> Result<()> {
    // 1. Activate Mostro node
    crate::api::settings::set_active_mostro_node(profile.pubkey.clone()).await?;

    // 2. Set default fiat currency
    if !profile.currency.is_empty() {
        let _ = crate::api::settings::set_default_fiat_code(Some(profile.currency.clone())).await;
    }

    // 3. Add relays from the profile
    for relay in &profile.relays {
        let trimmed = relay.trim();
        if !trimmed.is_empty() {
            let _ = crate::api::nostr::add_relay(trimmed.to_string()).await;
        }
    }

    // 4. Persist active community profile and payment methods
    if let Some(db) = crate::db::app_db::db() {
        let json = serde_json::to_string(&profile)?;
        db.set_setting(settings_keys::ACTIVE_COMMUNITY_PROFILE, &json).await?;

        let methods_json = serde_json::to_string(&profile.payment_methods)?;
        db.set_setting(settings_keys::COMMUNITY_PAYMENT_METHODS, &methods_json).await?;

        // 5. Register linked node in custom nodes registry with its name
        // (Saves only pubkey + name; bond_percent, fees, and other variant data stay dynamic)
        let _ = crate::api::nodes::register_linked_node(
            db,
            &profile.pubkey,
            Some(&profile.name),
        )
        .await;
    }

    Ok(())
}

/// Retrieve the currently active [`CommunityProfile`], if any.
pub async fn get_active_community_profile() -> Result<Option<CommunityProfile>> {
    if let Some(db) = crate::db::app_db::db() {
        if let Some(json) = db.get_setting(settings_keys::ACTIVE_COMMUNITY_PROFILE).await? {
            if !json.trim().is_empty() {
                if let Ok(profile) = serde_json::from_str::<CommunityProfile>(&json) {
                    return Ok(Some(profile));
                }
            }
        }
    }
    Ok(None)
}

/// Retrieve the cached payment methods for the active community.
pub async fn get_community_payment_methods() -> Result<Vec<String>> {
    if let Some(db) = crate::db::app_db::db() {
        if let Some(json) = db.get_setting(settings_keys::COMMUNITY_PAYMENT_METHODS).await? {
            if !json.trim().is_empty() {
                if let Ok(methods) = serde_json::from_str::<Vec<String>>(&json) {
                    return Ok(methods);
                }
            }
        }
    }
    Ok(Vec::new())
}

/// Clear the active community profile, reverting to default node configuration.
pub async fn clear_active_community_profile() -> Result<()> {
    if let Some(db) = crate::db::app_db::db() {
        db.set_setting(settings_keys::ACTIVE_COMMUNITY_PROFILE, "").await?;
        db.set_setting(settings_keys::COMMUNITY_PAYMENT_METHODS, "[]").await?;
    }
    Ok(())
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use base64::engine::general_purpose::URL_SAFE_NO_PAD;
    use base64::Engine;

    fn sample_signing_key() -> (k256::schnorr::SigningKey, String) {
        let signing_key = k256::schnorr::SigningKey::random(&mut rand::thread_rng());
        let pubkey_bytes = signing_key.verifying_key().to_bytes();
        let pubkey_hex = hex::encode(pubkey_bytes);
        (signing_key, pubkey_hex)
    }

    fn sample_profile(
        signing_key: &k256::schnorr::SigningKey,
        pubkey_hex: &str,
    ) -> CommunityProfile {
        let mut profile = CommunityProfile {
            version: 1,
            name: "Bitcoin Medellín".to_string(),
            pubkey: pubkey_hex.to_string(),
            relays: vec![
                "wss://relay.mostro.network".to_string(),
                "wss://nostr.mom".to_string(),
            ],
            currency: "COP".to_string(),
            payment_methods: vec!["Bancolombia".to_string(), "Nequi".to_string()],
            fee_bps: 60,
            bond_percent: 3,
            website: Some("https://bitcoinmedellin.org".to_string()),
            contact: Some("operador@nostr.net".to_string()),
            signature: String::new(),
        };

        let digest = canonical_digest(&profile);
        let sig: k256::schnorr::Signature = signing_key.sign_raw(&digest, &[0u8; 32]).unwrap();
        profile.signature = hex::encode(sig.to_bytes());
        profile
    }

    #[test]
    fn signature_verification_valid() {
        let (sk, pk) = sample_signing_key();
        let profile = sample_profile(&sk, &pk);
        assert!(verify_community_signature(&profile));
    }

    #[test]
    fn signature_verification_fails_on_tampered_name() {
        let (sk, pk) = sample_signing_key();
        let mut profile = sample_profile(&sk, &pk);
        profile.name = "Bitcoin Cali".to_string();
        assert!(!verify_community_signature(&profile));
    }

    #[test]
    fn signature_verification_fails_on_tampered_pubkey() {
        let (sk, pk) = sample_signing_key();
        let mut profile = sample_profile(&sk, &pk);
        let (_, other_pk) = sample_signing_key();
        profile.pubkey = other_pk;
        assert!(!verify_community_signature(&profile));
    }

    #[test]
    fn parse_json_payload_direct() {
        let (sk, pk) = sample_signing_key();
        let profile = sample_profile(&sk, &pk);
        let json = serde_json::to_string(&profile).unwrap();

        let parsed = parse_community_payload(json).unwrap();
        assert_eq!(parsed, profile);
        assert!(verify_community_signature(&parsed));
    }

    #[test]
    fn parse_deep_link_base64url() {
        let (sk, pk) = sample_signing_key();
        let profile = sample_profile(&sk, &pk);
        let json = serde_json::to_string(&profile).unwrap();
        let encoded = URL_SAFE_NO_PAD.encode(json.as_bytes());
        let deep_link = format!("mostro://community/{encoded}");

        let parsed = parse_community_payload(deep_link).unwrap();
        assert_eq!(parsed.name, "Bitcoin Medellín");
        assert_eq!(parsed.currency, "COP");
        assert!(verify_community_signature(&parsed));
    }

    #[test]
    fn parse_web_link_base64url() {
        let (sk, pk) = sample_signing_key();
        let profile = sample_profile(&sk, &pk);
        let json = serde_json::to_string(&profile).unwrap();
        let encoded = URL_SAFE_NO_PAD.encode(json.as_bytes());
        let web_link = format!("https://mostro.network/c/{encoded}");

        let parsed = parse_community_payload(web_link).unwrap();
        assert_eq!(parsed.name, "Bitcoin Medellín");
        assert_eq!(parsed.fee_bps, 60);
        assert!(verify_community_signature(&parsed));
    }

    #[test]
    fn parse_rejects_invalid_currency() {
        let (sk, pk) = sample_signing_key();
        let mut profile = sample_profile(&sk, &pk);
        profile.currency = "INVALID".to_string();
        let json = serde_json::to_string(&profile).unwrap();

        let err = parse_community_payload(json).unwrap_err();
        assert!(err.to_string().contains("InvalidCurrency"));
    }

    #[test]
    fn parse_nip19_profile_fallback() {
        let keys = Keys::generate();
        let relay = RelayUrl::parse("wss://relay.mostro.network").unwrap();
        let nprofile = Nip19Profile::new(keys.public_key(), vec![relay])
            .to_bech32()
            .unwrap();

        let uri = format!("nostr:{nprofile}");
        let parsed = parse_community_payload(uri).unwrap();
        assert_eq!(parsed.pubkey, keys.public_key().to_hex());
        assert_eq!(parsed.relays, vec!["wss://relay.mostro.network"]);
        assert_eq!(parsed.currency, "USD");
    }
}
