// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_and_validate_json`, `parse_nip19_community`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`

/// Compute the SHA-256 digest of the canonical profile fields for signature verification.
Future<U8Array32> canonicalDigest({required CommunityProfile profile}) =>
    RustLib.instance.api.crateApiCommunityCanonicalDigest(profile: profile);

/// Verify the Schnorr signature of a CommunityProfile against its `pubkey`.
///
/// Returns `true` if the signature is valid, `false` otherwise.
Future<bool> verifyCommunitySignature({required CommunityProfile profile}) =>
    RustLib.instance.api
        .crateApiCommunityVerifyCommunitySignature(profile: profile);

/// Parse a raw input string (deep link, URL, Base64/Base64URL JSON, or nprofile)
/// into a validated [`CommunityProfile`].
///
/// **Errors**:
/// - `InvalidCommunityPayload`: Malformed JSON or unreadable encoding.
/// - `InvalidPubkey`: If the embedded pubkey is not a valid 64-char hex or Nostr key.
/// - `InvalidCurrency`: If currency is not a 3-letter ISO code.
Future<CommunityProfile> parseCommunityPayload({required String input}) =>
    RustLib.instance.api.crateApiCommunityParseCommunityPayload(input: input);

/// Apply a confirmed [`CommunityProfile`] to the active application state:
/// 1. Activates the community Mostro node pubkey.
/// 2. Sets the default fiat currency.
/// 3. Registers community relays in the pool.
/// 4. Persists the active profile and accepted payment methods.
Future<void> applyCommunityProfile({required CommunityProfile profile}) =>
    RustLib.instance.api
        .crateApiCommunityApplyCommunityProfile(profile: profile);

/// Retrieve the currently active [`CommunityProfile`], if any.
Future<CommunityProfile?> getActiveCommunityProfile() =>
    RustLib.instance.api.crateApiCommunityGetActiveCommunityProfile();

/// Retrieve the cached payment methods for the active community.
Future<List<String>> getCommunityPaymentMethods() =>
    RustLib.instance.api.crateApiCommunityGetCommunityPaymentMethods();

/// Clear the active community profile, reverting to default node configuration.
Future<void> clearActiveCommunityProfile() =>
    RustLib.instance.api.crateApiCommunityClearActiveCommunityProfile();

/// A community configuration profile signed by the community node operator.
class CommunityProfile {
  /// Schema version (currently 1).
  final int version;

  /// Human-readable community name (e.g. "Bitcoin Medellín").
  final String name;

  /// 64-character lowercase hex Nostr public key of the Mostro daemon.
  final String pubkey;

  /// List of WebSocket relay URLs used by the community.
  final List<String> relays;

  /// Primary ISO 4217 fiat currency code (e.g. "COP", "USD", "EUR").
  final String currency;

  /// Prioritized accepted payment methods for this community.
  final List<String> paymentMethods;

  /// Community trade fee in basis points (e.g. 60 = 0.6%).
  final int feeBps;

  /// Required anti-abuse guarantee / bond percentage (e.g. 3 = 3%).
  final int bondPercent;

  /// Optional community website link.
  final String? website;

  /// Optional operator contact info (Nostr npub, Telegram, or email).
  final String? contact;

  /// 64-byte hex (128 char) Schnorr signature over the canonical payload.
  final String signature;

  const CommunityProfile({
    required this.version,
    required this.name,
    required this.pubkey,
    required this.relays,
    required this.currency,
    required this.paymentMethods,
    required this.feeBps,
    required this.bondPercent,
    this.website,
    this.contact,
    required this.signature,
  });

  @override
  int get hashCode =>
      version.hashCode ^
      name.hashCode ^
      pubkey.hashCode ^
      relays.hashCode ^
      currency.hashCode ^
      paymentMethods.hashCode ^
      feeBps.hashCode ^
      bondPercent.hashCode ^
      website.hashCode ^
      contact.hashCode ^
      signature.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityProfile &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          name == other.name &&
          pubkey == other.pubkey &&
          relays == other.relays &&
          currency == other.currency &&
          paymentMethods == other.paymentMethods &&
          feeBps == other.feeBps &&
          bondPercent == other.bondPercent &&
          website == other.website &&
          contact == other.contact &&
          signature == other.signature;
}
