// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// Every payment method this device keeps details for, in the order each was
/// first saved. Empty when it keeps none.
///
/// Errors: `StorageUnavailable` before `init_db`.
Future<List<PaymentDetails>> savedPaymentDetails() =>
    RustLib.instance.api.crateApiPaymentDetailsSavedPaymentDetails();

/// What is kept for each of `methods` — an order's, or the ones ticked on the
/// Sell tab — in their order and their spelling. `details` is empty where
/// nothing is kept, and an empty name is skipped. A method is found whatever
/// its case or outer spaces.
///
/// Errors: `StorageUnavailable` before `init_db`.
Future<List<PaymentDetails>> paymentDetailsFor({
  required List<String> methods,
}) => RustLib.instance.api.crateApiPaymentDetailsPaymentDetailsFor(
  methods: methods,
);

/// Keep `details` for `method` on this device, in place of what was kept for
/// it. Empty `details` forget the method.
///
/// Kept with the identity: generating or importing another one erases them.
///
/// Errors are markers: `StorageUnavailable`, `InvalidPaymentMethod` (no name,
/// or one past 100 characters), `PaymentDetailsTooLong` (past 1000).
Future<void> savePaymentDetails({
  required String method,
  required String details,
}) => RustLib.instance.api.crateApiPaymentDetailsSavePaymentDetails(
  method: method,
  details: details,
);

/// Send the seller's payment details to the buyer of `order_id`, over the
/// trade's end-to-end encrypted chat.
///
/// `content` is the message as the buyer will read it. Dart composes it —
/// it is prose — from the methods the seller left ticked.
///
/// Refused, with nothing sent, unless this user is the seller and the
/// escrow is locked (`active`, `fiat-sent` or `dispute` on the trade row).
/// Returns the message, now in the conversation, only once a relay accepted
/// it; from then on [`payment_details_sent_at`] answers for the order.
///
/// Errors are markers: `StorageUnavailable`, `MessageEmpty`,
/// `PaymentDetailsNoTrade`, `PaymentDetailsNotSeller`,
/// `PaymentDetailsEscrowNotLocked`, then those of the send —
/// `PaymentDetailsPeerUnknown` (the buyer's key is not here yet),
/// `NoRelayAccepted`, `MessageTooLarge`, `SendFailed`.
Future<ChatMessage> sendPaymentDetails({
  required String orderId,
  required String content,
}) => RustLib.instance.api.crateApiPaymentDetailsSendPaymentDetails(
  orderId: orderId,
  content: content,
);

/// When the payment details of `order_id` were sent from this device (unix
/// seconds), or `None` if they never were.
///
/// Errors: `StorageUnavailable` before `init_db`.
Future<PlatformInt64?> paymentDetailsSentAt({required String orderId}) =>
    RustLib.instance.api.crateApiPaymentDetailsPaymentDetailsSentAt(
      orderId: orderId,
    );

/// One payment method and what its seller is paid with.
class PaymentDetails {
  /// The method's name, as an order or the community's card writes it.
  final String method;

  /// Account, holder, phone — free text. Empty when nothing is kept.
  final String details;

  const PaymentDetails({required this.method, required this.details});

  @override
  int get hashCode => method.hashCode ^ details.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaymentDetails &&
          runtimeType == other.runtimeType &&
          method == other.method &&
          details == other.details;
}
